version: '3.8'

services:
  chatapp:
    container_name: mystory
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/mystory
